# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/cao2/Desktop/soci-master-af9a83b1cf7c69a17bf7ed9f1c24942b5f6e0618/soci-master-af9a83b1cf7c69a17bf7ed9f1c24942b5f6e0618/soc_ic/soc_ic.cache/wt [current_project]
set_property parent.project_path C:/Users/cao2/Desktop/soci-master-af9a83b1cf7c69a17bf7ed9f1c24942b5f6e0618/soci-master-af9a83b1cf7c69a17bf7ed9f1c24942b5f6e0618/soc_ic/soc_ic.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo c:/Users/cao2/Desktop/soci-master-af9a83b1cf7c69a17bf7ed9f1c24942b5f6e0618/soci-master-af9a83b1cf7c69a17bf7ed9f1c24942b5f6e0618/soc_ic/soc_ic.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/cao2/Desktop/oven/soc/defs.vhd
  C:/Users/cao2/Desktop/oven/soc/arbiter2_ack.vhd
  C:/Users/cao2/Desktop/oven/soc/arbiter6.vhd
  C:/Users/cao2/Desktop/oven/soc/arbiter6_ack.vhd
  C:/Users/cao2/Desktop/oven/soc/arbiter7.vhd
  C:/Users/cao2/Desktop/oven/soc/b_arbiter2.vhd
  C:/Users/cao2/Desktop/oven/soc/b_arbiter6.vhd
  C:/Users/cao2/Desktop/oven/soc/b_fifo.vhd
  C:/Users/cao2/Desktop/oven/soc/bmsg_fifo_m.vhd
  C:/Users/cao2/Desktop/oven/soc/util.vhd
  C:/Users/cao2/Desktop/oven/soc/rand.vhd
  C:/Users/cao2/Desktop/oven/soc/test.vhd
  C:/Users/cao2/Desktop/oven/soc/cache_req_m.vhd
  C:/Users/cao2/Desktop/oven/soc/fifo.vhd
  C:/Users/cao2/Desktop/oven/soc/fifo_snp.vhd
  C:/Users/cao2/Desktop/oven/soc/toper_chan_m.vhd
  C:/Users/cao2/Desktop/oven/soc/per_upreq_m.vhd
  C:/Users/cao2/Desktop/oven/soc/msg_fifo_m.vhd
  C:/Users/cao2/Desktop/oven/soc/per_write_m.vhd
  C:/Users/cao2/Desktop/oven/soc/wb_m.vhd
  C:/Users/cao2/Desktop/oven/soc/ic.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/cao2/Desktop/soci-master-af9a83b1cf7c69a17bf7ed9f1c24942b5f6e0618/soci-master-af9a83b1cf7c69a17bf7ed9f1c24942b5f6e0618/soc_ic/zedboard_master.xdc
set_property used_in_implementation false [get_files C:/Users/cao2/Desktop/soci-master-af9a83b1cf7c69a17bf7ed9f1c24942b5f6e0618/soci-master-af9a83b1cf7c69a17bf7ed9f1c24942b5f6e0618/soc_ic/zedboard_master.xdc]


synth_design -top ic -part xc7z020clg484-1


write_checkpoint -force -noxdef ic.dcp

catch { report_utilization -file ic_utilization_synth.rpt -pb ic_utilization_synth.pb }
