set_property SRC_FILE_INFO {cfile:C:/Users/cao2/Desktop/soci/soci/soc_ic/soc_ic.srcs/constrs_1/new/kinect7.xdc rfile:../../../soc_ic.srcs/constrs_1/new/kinect7.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFGCTRL_X0Y0 [get_cells xilinx_pad_inst_cb]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets reset_IBUF]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD12 [get_ports Clock]
set_property src_info {type:XDC file:1 line:884 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G12 [get_ports reset]
set_property src_info {type:XDC file:1 line:1166 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K24 [get_ports rx_in]
set_property src_info {type:XDC file:1 line:1168 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M19 [get_ports tx_out]
